import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { headers } from 'next/headers'

// ... existing imports

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers()
  const nonce = headersList.get('x-nonce') || ''

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Pass nonce to Next.js by using it in Script or just implicitly if configured? 
            Next.js automatically reads the nonce from the request headers if middleware sets it? 
            Actually, for App Router, we usually need to pass it to the relevant components.
            However, for built-in styles, Next.js 13+ usually handles it if the header is present?
            Let's at least read it to force dynamic rendering if needed and be ready to use it.
            For now, just reading it is a good step to ensure the layout is dynamic.
        */}
        {children}
      </body>
    </html>
  );
}
